# Лабораторна робота 1. Варіант 3




In [ ]:
#Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть його значення.

In [ ]:
import numpy as np
numbers = np.arange(2, 21, 2)
print(numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.

In [ ]:
import numpy as np
matrix = np.random.rand(3, 3)
print(matrix)

[[0.57440868 0.10746384 0.3099688 ]
 [0.35977806 0.42188751 0.15140504]
 [0.53884705 0.28021617 0.20405648]]


In [ ]:
#Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 20 та виведіть його значення.

In [ ]:
import numpy as np
random_matrix = np.random.randint(1, 21, size=(3, 3))
print(random_matrix)

[[12 18 18]
 [ 8 13  1]
 [20 20 19]]


In [ ]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть мінімальний елемент.

In [ ]:
import numpy as np
random_matrix_4x4 = np.random.rand(4, 4)
min_element = np.min(random_matrix_4x4)
print("Матриця 4x4:\n", random_matrix_4x4)
print("Мінімальний елемент:", min_element)

Матриця 4x4:
 [[0.96527029 0.15779003 0.79961455 0.63803099]
 [0.50015823 0.56300482 0.40756601 0.57799795]
 [0.13285807 0.53206678 0.11412975 0.27152211]
 [0.10881381 0.97779887 0.39378432 0.83094131]]
Мінімальний елемент: 0.10881381108337862


In [ ]:
#Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні
# від 1 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
import numpy as np
array1 = np.random.randint(1, 16, size=7)
array2 = np.random.randint(1, 16, size=7)
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
print("Перший масив:", array1)
print("Другий масив:", array2)
print("Результат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)

Перший масив: [ 3  8  8 15  1  3  6]
Другий масив: [ 2  1  3  8  3 11 15]
Результат додавання: [ 5  9 11 23  4 14 21]
Результат віднімання: [ 1  7  5  7 -2 -8 -9]
Результат множення: [  6   8  24 120   3  33  90]


In [ ]:
#Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та знайдіть їх добуток.

In [ ]:
import numpy as np
matrix1 = np.random.randint(3, 31, size=(3, 3))
matrix2 = np.random.randint(3, 31, size=(3, 3))
matrix_add = np.dot(matrix1, matrix2)
print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Добуток матриць:\n", matrix_add)

Перша матриця:
 [[29 14 24]
 [ 5  4  9]
 [ 3  7 25]]
Друга матриця:
 [[17 19 17]
 [27 12 17]
 [25 28  7]]
Добуток матриць:
 [[1471 1391  899]
 [ 418  395  216]
 [ 865  841  345]]


In [ ]:
#Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 7 та перемножте їх між собою.

In [ ]:
import numpy as np
matrix1 = np.random.randint(1, 8, size=(4, 2))
matrix2 = np.random.randint(1, 8, size=(2, 5))
matrix_add = np.dot(matrix1, matrix2)
print("Перша матриця (4x2):\n", matrix1)
print("Друга матриця (2x5):\n", matrix2)
print("Добуток матриць:\n", matrix_add)

Перша матриця (4x2):
 [[1 2]
 [7 7]
 [1 4]
 [2 1]]
Друга матриця (2x5):
 [[1 5 3 3 5]
 [7 6 7 6 4]]
Добуток матриць:
 [[15 17 17 15 13]
 [56 77 70 63 63]
 [29 29 31 27 21]
 [ 9 16 13 12 14]]


In [ ]:
#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю.

In [ ]:
import numpy as np
matrix = np.random.randint(1, 9, size=(2, 2))
print("Оригінальна матриця:")
print(matrix)
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця є сингулярною і не має оберненої.")

Оригінальна матриця:
[[7 2]
 [1 2]]
Обернена матриця:
[[ 0.16666667 -0.16666667]
 [-0.08333333  0.58333333]]


In [ ]:
#Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
import numpy as np
matrix = np.random.rand(2, 3)
print("Оригінальна матриця:")
print(matrix)
transposed_matrix = matrix.T
print("Транспонована матриця:")
print(transposed_matrix)

Оригінальна матриця:
[[0.1942257  0.22029501 0.35261946]
 [0.89332556 0.99243531 0.08223181]]
Транспонована матриця:
[[0.1942257  0.89332556]
 [0.22029501 0.99243531]
 [0.35261946 0.08223181]]


In [ ]:
#Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.

In [ ]:
import numpy as np
matrix = np.random.randint(1, 11, size=(3, 4))
print("Матриця 3x4:")
print(matrix)
vector = np.random.randint(1, 11, size=(4, 1))
print("Вектор 4x1:")
print(vector)
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)

Матриця 3x4:
[[9 5 8 8]
 [2 8 5 3]
 [3 9 9 5]]
Вектор 4x1:
[[ 4]
 [ 9]
 [10]
 [10]]
Добуток матриці на вектор:
[[241]
 [160]
 [233]]


In [ ]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1,
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [ ]:
import numpy as np
matrix = np.random.rand(2, 3)
print("Матриця 2x3:")
print(matrix)
vector = np.random.randint(1, 11, size=(3, 1))
print("Вектор 3x1:")
print(vector)
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)

Матриця 2x3:
[[0.57606125 0.75365915 0.79687185]
 [0.88248328 0.87030087 0.04998316]]
Вектор 3x1:
[[10]
 [10]
 [ 2]]
Добуток матриці на вектор:
[[14.89094768]
 [17.62780778]]


In [ ]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [ ]:
import numpy as np
matrix1 = np.random.randint(1, 11, size=(4, 4))
print("Перша матриця 4x4:")
print(matrix1)
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Друга матриця 4x4:")
print(matrix2)
sum_matrix = matrix1 + matrix2
print("Сума матриць:")
print(sum_matrix)

Перша матриця 4x4:
[[2 6 6 8]
 [7 9 7 5]
 [8 2 4 1]
 [1 8 9 7]]
Друга матриця 4x4:
[[ 4  9  6  8]
 [ 7  4  5  7]
 [ 4  6  3 10]
 [ 3  9  8  3]]
Сума матриць:
[[ 6 15 12 16]
 [14 13 12 12]
 [12  8  7 11]
 [ 4 17 17 10]]


In [ ]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть їх добуток.

In [ ]:
import numpy as np
matrix1 = 2 * np.random.rand(4, 4) - 1
print("Перша матриця 4x4:")
print(matrix1)
matrix2 = 2 * np.random.rand(4, 4) - 1
print("Друга матриця 4x4:")
print(matrix2)
product_matrix = np.dot(matrix1, matrix2)
print("Добуток матриць:")
print(product_matrix)

Перша матриця 4x4:
[[ 0.34362775 -0.31326021 -0.96689834 -0.26513273]
 [ 0.10490623  0.37825504  0.17367143 -0.8937116 ]
 [-0.14836766  0.82450654  0.23793412 -0.11163807]
 [ 0.38153139  0.38031646 -0.07852931 -0.26758529]]
Друга матриця 4x4:
[[ 0.40764397  0.37643381 -0.55396793 -0.83419795]
 [ 0.58510361  0.70706245  0.8382136   0.43926883]
 [ 0.35700012  0.75431395 -0.95288514 -0.66104039]
 [ 0.59834099 -0.26115968 -0.43676688  0.21292729]]
Добуток матриць:
[[-0.5470345  -0.75224435  0.58420653  0.15844585]
 [-0.20866078  0.67134441  0.48379854 -0.22645633]
 [ 0.44008544  0.7357594   0.59533944  0.30489316]
 [ 0.18991129  0.42317554  0.29913208 -0.15627671]]


In [ ]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму елементів матриці.

In [ ]:
import numpy as np
matrix = 2 * np.random.rand(3, 3) - 1
print("Матриця 3x3:")
print(matrix)
sum_elements = np.sum(matrix)
print("Сума елементів матриці:")
print(sum_elements)

Матриця 3x3:
[[ 0.77616464  0.9517044   0.86991857]
 [ 0.81462845  0.56569743 -0.90632544]
 [ 0.36420431 -0.49068308 -0.51769629]]
Сума елементів матриці:
2.427612990665568


In [ ]:
#Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
import numpy as np
matrix = np.random.rand(5, 5) - 0.5
print("Матриця 5x5:")
print(matrix)
sums = np.sum(matrix, axis=1)
print("Вектор-стовпчик, що містить суму елементів кожного рядка:")
print(sums)

Матриця 5x5:
[[ 0.12246823  0.49822063 -0.26072714  0.19669304  0.27016178]
 [ 0.44435381  0.24611628 -0.40576252 -0.44417591 -0.12968873]
 [ 0.27654536 -0.01246543  0.1418621   0.30895821 -0.20361181]
 [-0.03490685  0.17631471  0.17244398 -0.11817054  0.15656408]
 [-0.19314065  0.09133471 -0.31942155  0.32232197 -0.18081935]]
Вектор-стовпчик, що містить суму елементів кожного рядка:
[ 0.82681653 -0.28915707  0.51128843  0.35224539 -0.27972487]


In [ ]:
#Висновок - на даній лабораторній роботі, я розробила програми для машиного навчання з елементами лінійної алгебри та створила репозиторій на GitHub.
#https://github.com/dassha5/machine_learning